Update the documentation for issue-31
Set the default nodejs version to 12 as per https://github.com/perara/wg-manager/issues/31
Also set the pip install to pip3 as we are using python3.

This was causing some issues with the wheel setup
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for python-multipart
  ERROR: Failed building wheel for sqlalchemy-utils
  ERROR: Failed building wheel for Tempita

Also set these as being used by sudo otherwise the venv has an issue with the permissions

ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/opt/wg-manager/wg_dashboard_backend/venv/lib/python3.8/site-packages/typing_extensions.py'
Consider using the `--user` option or check the permissions.

Attempting to use the --user flag does not work

This works (once the requirements.txt file has been edited to set the sqlalchemy version to < 1.4.0 due to a versioning issues with API calls)
ImportError: cannot import name '_ColumnEntity' from 'sqlalchemy.orm.query' (/opt/wg-manager/wg_dashboard_backend/venv/lib/python3.8/site-packages/sqlalchemy/orm/query.py)
https://stackoverflow.com/questions/66644975/importerror-cannot-import-name-columnentity-from-sqlalchemy-orm-query


Working as below
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)